window.debtorStatusData = {
  "2025-10": {
    "stateStatus": [
      {
        "state": "Pahang",
        "total": 399,
        "active": 376,
        "inactive": 0,
        "missing": 23,
        "activeRate": 94.2,
        "sales": 1194955.97
      },
      {
        "state": "Kelantan",
        "total": 375,
        "active": 370,
        "inactive": 0,
        "missing": 5,
        "activeRate": 98.7,
        "sales": 408219.75
      },
      {
        "state": "Terengganu",
        "total": 267,
        "active": 258,
        "inactive": 0,
        "missing": 9,
        "activeRate": 96.6,
        "sales": 398656.0
      }
    ],
    "agentStatus": [
      {
        "state": "Kelantan",
        "agent": "BEN",
        "total": 70,
        "active": 68,
        "inactive": 0,
        "missing": 2,
        "activeRate": 97.1,
        "sales": 42372.0
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "total": 79,
        "active": 78,
        "inactive": 0,
        "missing": 1,
        "activeRate": 98.7,
        "sales": 178465.25
      },
      {
        "state": "Kelantan",
        "agent": "KI-MI",
        "total": 123,
        "active": 121,
        "inactive": 0,
        "missing": 2,
        "activeRate": 98.4,
        "sales": 51361.0
      },
      {
        "state": "Kelantan",
        "agent": "YI",
        "total": 105,
        "active": 105,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 136021.5
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "total": 93,
        "active": 84,
        "inactive": 0,
        "missing": 9,
        "activeRate": 90.3,
        "sales": 314930.3
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "total": 94,
        "active": 94,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 227749.29
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "total": 101,
        "active": 98,
        "inactive": 0,
        "missing": 3,
        "activeRate": 97.0,
        "sales": 405394.02
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "total": 111,
        "active": 100,
        "inactive": 0,
        "missing": 11,
        "activeRate": 90.1,
        "sales": 246882.36
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "total": 142,
        "active": 138,
        "inactive": 0,
        "missing": 4,
        "activeRate": 97.2,
        "sales": 146294.0
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "total": 126,
        "active": 121,
        "inactive": 0,
        "missing": 5,
        "activeRate": 96.0,
        "sales": 252362.0
      }
    ],
    "watchlist": [
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS139",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 2907.0,
        "qty": 76.0,
        "docs": 9,
        "topSku": "EVO",
        "lastDate": "2025-10-31"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J211",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 2135.5,
        "qty": 59.0,
        "docs": 5,
        "topSku": "TR-002",
        "lastDate": "2025-10-29"
      },
      {
        "state": "Kelantan",
        "agent": "KI-MI",
        "code": "300-KV184",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1407.0,
        "qty": 34.0,
        "docs": 3,
        "topSku": "EVO",
        "lastDate": "2025-10-20"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D255",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1329.9,
        "qty": 38.0,
        "docs": 4,
        "topSku": "CM-002",
        "lastDate": "2025-10-31"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY299",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1100.0,
        "qty": 25.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2025-10-09"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D270",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1028.0,
        "qty": 27.0,
        "docs": 3,
        "topSku": "SKNW",
        "lastDate": "2025-10-21"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D033",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 870.0,
        "qty": 20.0,
        "docs": 2,
        "topSku": "CM-002",
        "lastDate": "2025-10-14"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "300-C253",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 768.5,
        "qty": 21.0,
        "docs": 4,
        "topSku": "TR-002",
        "lastDate": "2025-10-29"
      },
      {
        "state": "Kelantan",
        "agent": "KI-MI",
        "code": "300-KV215",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 735.0,
        "qty": 15.0,
        "docs": 3,
        "topSku": "CM-002",
        "lastDate": "2025-10-27"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J221",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 607.0,
        "qty": 19.0,
        "docs": 1,
        "topSku": "BISON-R",
        "lastDate": "2025-10-08"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D057",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 585.0,
        "qty": 15.0,
        "docs": 2,
        "topSku": "90",
        "lastDate": "2025-10-15"
      },
      {
        "state": "Kelantan",
        "agent": "BEN",
        "code": "300-KB073",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 531.0,
        "qty": 16.0,
        "docs": 2,
        "topSku": "SKNR",
        "lastDate": "2025-10-22"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "3EV-Q0203",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 505.0,
        "qty": 13.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2025-10-17"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D254",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 465.0,
        "qty": 13.0,
        "docs": 2,
        "topSku": "SKNR",
        "lastDate": "2025-10-21"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J203",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 461.1,
        "qty": 11.0,
        "docs": 1,
        "topSku": "TR-002",
        "lastDate": "2025-10-07"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J222",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 413.0,
        "qty": 11.0,
        "docs": 2,
        "topSku": "SKNR",
        "lastDate": "2025-10-29"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "3EV-L0613",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 360.0,
        "qty": 10.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2025-10-03"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D214",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 290.5,
        "qty": 7.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2025-10-30"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS243",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 290.0,
        "qty": 8.0,
        "docs": 3,
        "topSku": "EVO",
        "lastDate": "2025-10-31"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "3EV-D0151",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 280.0,
        "qty": 10.0,
        "docs": 1,
        "topSku": "BISON-R",
        "lastDate": "2025-10-14"
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "code": "300-KT185",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 270.0,
        "qty": 5.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2025-10-30"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY292",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 244.0,
        "qty": 6.0,
        "docs": 2,
        "topSku": "BISON-R",
        "lastDate": "2025-10-16"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-FE249",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 235.0,
        "qty": 5.0,
        "docs": 1,
        "topSku": "SKNW",
        "lastDate": "2025-10-29"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J234",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 234.0,
        "qty": 5.0,
        "docs": 2,
        "topSku": "TR20",
        "lastDate": "2025-10-22"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "3EV-Q0215",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 216.0,
        "qty": 4.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2025-10-23"
      },
      {
        "state": "Kelantan",
        "agent": "BEN",
        "code": "3EV-J0110",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 202.0,
        "qty": 4.0,
        "docs": 1,
        "topSku": "TR-002",
        "lastDate": "2025-10-17"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "300-C254",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 180.0,
        "qty": 4.0,
        "docs": 1,
        "topSku": "DPM EVO",
        "lastDate": "2025-10-15"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D287",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 144.0,
        "qty": 4.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2025-10-02"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J210",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 111.0,
        "qty": 3.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2025-10-09"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY053",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 108.0,
        "qty": 3.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2025-10-17"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "3EV-Q0019",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 94.0,
        "qty": 2.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2025-10-02"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS269",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 90.0,
        "qty": 2.0,
        "docs": 2,
        "topSku": "CMX",
        "lastDate": "2025-10-23"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D290",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 74.0,
        "qty": 2.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2025-10-30"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "3EV-Q0336",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 54.0,
        "qty": 1.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2025-10-31"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS292",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 54.0,
        "qty": 1.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2025-10-24"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "3EV-Q0141",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 47.0,
        "qty": 1.0,
        "docs": 1,
        "topSku": "LC20",
        "lastDate": "2025-10-23"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY260",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 29.5,
        "qty": 1.0,
        "docs": 1,
        "topSku": "IFACE R",
        "lastDate": "2025-10-31"
      }
    ]
  },
  "2025-11": {
    "stateStatus": [
      {
        "state": "Pahang",
        "total": 405,
        "active": 383,
        "inactive": 0,
        "missing": 22,
        "activeRate": 94.6,
        "sales": 1050105.41
      },
      {
        "state": "Kelantan",
        "total": 379,
        "active": 376,
        "inactive": 0,
        "missing": 3,
        "activeRate": 99.2,
        "sales": 364438.5
      },
      {
        "state": "Terengganu",
        "total": 256,
        "active": 250,
        "inactive": 0,
        "missing": 6,
        "activeRate": 97.7,
        "sales": 347755.0
      }
    ],
    "agentStatus": [
      {
        "state": "Kelantan",
        "agent": "BEN",
        "total": 69,
        "active": 68,
        "inactive": 0,
        "missing": 1,
        "activeRate": 98.6,
        "sales": 37358.1
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "total": 83,
        "active": 83,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 155186.5
      },
      {
        "state": "Kelantan",
        "agent": "KI-MI",
        "total": 112,
        "active": 110,
        "inactive": 0,
        "missing": 2,
        "activeRate": 98.2,
        "sales": 48313.5
      },
      {
        "state": "Kelantan",
        "agent": "YI",
        "total": 116,
        "active": 115,
        "inactive": 0,
        "missing": 1,
        "activeRate": 99.1,
        "sales": 123580.4
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "total": 99,
        "active": 89,
        "inactive": 0,
        "missing": 10,
        "activeRate": 89.9,
        "sales": 280646.25
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "total": 94,
        "active": 94,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 252104.14
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "total": 110,
        "active": 106,
        "inactive": 0,
        "missing": 4,
        "activeRate": 96.4,
        "sales": 311293.25
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "total": 102,
        "active": 94,
        "inactive": 0,
        "missing": 8,
        "activeRate": 92.2,
        "sales": 206061.77
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "total": 138,
        "active": 136,
        "inactive": 0,
        "missing": 2,
        "activeRate": 98.6,
        "sales": 120841.0
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "total": 118,
        "active": 114,
        "inactive": 0,
        "missing": 4,
        "activeRate": 96.6,
        "sales": 226914.0
      }
    ],
    "watchlist": [
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "300-C631",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 6680.0,
        "qty": 180.0,
        "docs": 1,
        "topSku": "90",
        "lastDate": "2025-11-13"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS139",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1696.0,
        "qty": 44.0,
        "docs": 5,
        "topSku": "CM-002",
        "lastDate": "2025-11-21"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J211",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1652.0,
        "qty": 45.0,
        "docs": 4,
        "topSku": "TR-002",
        "lastDate": "2025-11-26"
      },
      {
        "state": "Kelantan",
        "agent": "KI-MI",
        "code": "300-KV184",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1530.0,
        "qty": 37.0,
        "docs": 2,
        "topSku": "CMP",
        "lastDate": "2025-11-17"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D255",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1252.5,
        "qty": 34.0,
        "docs": 2,
        "topSku": "CMP",
        "lastDate": "2025-11-14"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D270",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1216.2,
        "qty": 32.0,
        "docs": 3,
        "topSku": "SKNW",
        "lastDate": "2025-11-25"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "3EV-Q0203",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1033.0,
        "qty": 28.0,
        "docs": 2,
        "topSku": "CMP",
        "lastDate": "2025-11-27"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J221",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 950.5,
        "qty": 26.0,
        "docs": 2,
        "topSku": "SKNR",
        "lastDate": "2025-11-14"
      },
      {
        "state": "Kelantan",
        "agent": "YI",
        "code": "300-KV215",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 686.0,
        "qty": 14.0,
        "docs": 2,
        "topSku": "CM-002",
        "lastDate": "2025-11-27"
      },
      {
        "state": "Kelantan",
        "agent": "BEN",
        "code": "300-KB073",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 479.0,
        "qty": 12.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2025-11-05"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J222",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 415.0,
        "qty": 10.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2025-11-25"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "3EV-Q0336",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 378.0,
        "qty": 7.0,
        "docs": 2,
        "topSku": "CMP",
        "lastDate": "2025-11-08"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J234",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 370.0,
        "qty": 10.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2025-11-11"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS321",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 366.0,
        "qty": 7.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2025-11-25"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D315",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 327.0,
        "qty": 9.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2025-11-27"
      },
      {
        "state": "Kelantan",
        "agent": "KI-MI",
        "code": "300-KV215",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 294.0,
        "qty": 6.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2025-11-16"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D033",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 289.5,
        "qty": 7.0,
        "docs": 2,
        "topSku": "CM-002",
        "lastDate": "2025-11-25"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "3EV-D0151",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 280.0,
        "qty": 10.0,
        "docs": 1,
        "topSku": "BISON-R",
        "lastDate": "2025-11-13"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "3EV-Q0141",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 235.0,
        "qty": 5.0,
        "docs": 3,
        "topSku": "LC20",
        "lastDate": "2025-11-27"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "300-C254",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 202.0,
        "qty": 4.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2025-11-12"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J203",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 185.0,
        "qty": 5.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2025-11-11"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "3EV-R0185",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 162.0,
        "qty": 3.0,
        "docs": 1,
        "topSku": "CMX",
        "lastDate": "2025-11-27"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D254",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 148.0,
        "qty": 4.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2025-11-03"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY303",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 111.0,
        "qty": 3.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2025-11-27"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J186",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 74.5,
        "qty": 2.0,
        "docs": 1,
        "topSku": "DPM EVO",
        "lastDate": "2025-11-07"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY116",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 56.0,
        "qty": 2.0,
        "docs": 1,
        "topSku": "BISON-R",
        "lastDate": "2025-11-28"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY117",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 56.0,
        "qty": 2.0,
        "docs": 1,
        "topSku": "BISON-R",
        "lastDate": "2025-11-28"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J244",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 54.0,
        "qty": 1.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2025-11-25"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J245",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 54.0,
        "qty": 1.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2025-11-25"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D307",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 54.0,
        "qty": 1.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2025-11-24"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY153",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 36.0,
        "qty": 1.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2025-11-27"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "300-C138",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 29.1,
        "qty": 1.0,
        "docs": 1,
        "topSku": "IFACE M",
        "lastDate": "2025-11-18"
      }
    ]
  },
  "2025-12": {
    "stateStatus": [
      {
        "state": "Pahang",
        "total": 388,
        "active": 376,
        "inactive": 0,
        "missing": 12,
        "activeRate": 96.9,
        "sales": 1163728.92
      },
      {
        "state": "Terengganu",
        "total": 349,
        "active": 344,
        "inactive": 0,
        "missing": 5,
        "activeRate": 98.6,
        "sales": 562481.0
      },
      {
        "state": "Kelantan",
        "total": 357,
        "active": 356,
        "inactive": 0,
        "missing": 1,
        "activeRate": 99.7,
        "sales": 414637.45
      }
    ],
    "agentStatus": [
      {
        "state": "Kelantan",
        "agent": "BEN",
        "total": 53,
        "active": 52,
        "inactive": 0,
        "missing": 1,
        "activeRate": 98.1,
        "sales": 42476.5
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "total": 81,
        "active": 81,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 199759.35
      },
      {
        "state": "Kelantan",
        "agent": "KI-MI",
        "total": 119,
        "active": 119,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 53952.5
      },
      {
        "state": "Kelantan",
        "agent": "YI",
        "total": 104,
        "active": 104,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 118449.1
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "total": 95,
        "active": 90,
        "inactive": 0,
        "missing": 5,
        "activeRate": 94.7,
        "sales": 330575.87
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "total": 93,
        "active": 93,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 261698.5
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "total": 103,
        "active": 103,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 345822.24
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "total": 97,
        "active": 90,
        "inactive": 0,
        "missing": 7,
        "activeRate": 92.8,
        "sales": 225632.31
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "total": 136,
        "active": 135,
        "inactive": 0,
        "missing": 1,
        "activeRate": 99.3,
        "sales": 134002.5
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "total": 113,
        "active": 112,
        "inactive": 0,
        "missing": 1,
        "activeRate": 99.1,
        "sales": 250288.5
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "total": 101,
        "active": 98,
        "inactive": 0,
        "missing": 3,
        "activeRate": 97.0,
        "sales": 178190.0
      }
    ],
    "watchlist": [
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "3EV-Q0203",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 2293.0,
        "qty": 64.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2025-12-11"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "3EV-L0392",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1628.0,
        "qty": 44.0,
        "docs": 5,
        "topSku": "SKNR",
        "lastDate": "2025-12-31"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D270",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1427.0,
        "qty": 40.0,
        "docs": 4,
        "topSku": "SKNW",
        "lastDate": "2025-12-30"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J221",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1354.25,
        "qty": 41.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2025-12-10"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J222",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 715.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2025-12-23"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D315",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 709.0,
        "qty": 19.0,
        "docs": 2,
        "topSku": "CMP",
        "lastDate": "2025-12-29"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D299",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 640.0,
        "qty": 16.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2025-12-08"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D255",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 522.0,
        "qty": 16.0,
        "docs": 3,
        "topSku": "IFACE B",
        "lastDate": "2025-12-26"
      },
      {
        "state": "Kelantan",
        "agent": "BEN",
        "code": "300-BR083",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 370.0,
        "qty": 10.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2025-12-10"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D254",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 223.0,
        "qty": 6.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2025-12-16"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D290",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 185.0,
        "qty": 5.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2025-12-11"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS321",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 162.0,
        "qty": 3.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2025-12-17"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "3EV-R0025",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 146.0,
        "qty": 3.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2025-12-10"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J211",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 108.0,
        "qty": 3.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2025-12-31"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "3EV-Q0141",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 47.0,
        "qty": 1.0,
        "docs": 1,
        "topSku": "LC20",
        "lastDate": "2025-12-11"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J210",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 37.0,
        "qty": 1.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2025-12-04"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "3EV-L0058",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 37.0,
        "qty": 1.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2025-12-04"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY007",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 36.0,
        "qty": 1.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2025-12-27"
      }
    ]
  },
  "2026-01": {
    "stateStatus": [
      {
        "state": "Pahang",
        "total": 382,
        "active": 375,
        "inactive": 0,
        "missing": 7,
        "activeRate": 98.2,
        "sales": 1180110.18
      },
      {
        "state": "Terengganu",
        "total": 343,
        "active": 339,
        "inactive": 0,
        "missing": 4,
        "activeRate": 98.8,
        "sales": 615271.0
      },
      {
        "state": "Kelantan",
        "total": 376,
        "active": 375,
        "inactive": 0,
        "missing": 1,
        "activeRate": 99.7,
        "sales": 473917.1
      }
    ],
    "agentStatus": [
      {
        "state": "Kelantan",
        "agent": "BEN",
        "total": 72,
        "active": 71,
        "inactive": 0,
        "missing": 1,
        "activeRate": 98.6,
        "sales": 47021.4
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "total": 79,
        "active": 79,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 219063.8
      },
      {
        "state": "Kelantan",
        "agent": "KI-MI",
        "total": 111,
        "active": 111,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 62532.0
      },
      {
        "state": "Kelantan",
        "agent": "YI",
        "total": 116,
        "active": 116,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 145299.9
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "total": 99,
        "active": 95,
        "inactive": 0,
        "missing": 4,
        "activeRate": 96.0,
        "sales": 328218.38
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "total": 96,
        "active": 96,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 305050.77
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "total": 98,
        "active": 98,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 342951.6
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "total": 90,
        "active": 87,
        "inactive": 0,
        "missing": 3,
        "activeRate": 96.7,
        "sales": 203889.43
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "total": 134,
        "active": 133,
        "inactive": 0,
        "missing": 1,
        "activeRate": 99.3,
        "sales": 143001.5
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "total": 110,
        "active": 109,
        "inactive": 0,
        "missing": 1,
        "activeRate": 99.1,
        "sales": 278618.0
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "total": 100,
        "active": 98,
        "inactive": 0,
        "missing": 2,
        "activeRate": 98.0,
        "sales": 193651.5
      }
    ],
    "watchlist": [
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "3EV-L0392",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1611.0,
        "qty": 36.0,
        "docs": 4,
        "topSku": "JDB",
        "lastDate": "2026-01-31"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D270",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1254.0,
        "qty": 33.0,
        "docs": 4,
        "topSku": "SKNW",
        "lastDate": "2026-01-26"
      },
      {
        "state": "Kelantan",
        "agent": "BEN",
        "code": "300-BR083",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 740.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2026-01-14"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D255",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 571.9,
        "qty": 18.0,
        "docs": 3,
        "topSku": "IFACE B",
        "lastDate": "2026-01-16"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J222",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 452.5,
        "qty": 13.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2026-01-10"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "3EV-R0025",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 322.0,
        "qty": 7.0,
        "docs": 2,
        "topSku": "EVO",
        "lastDate": "2026-01-07"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J221",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 170.0,
        "qty": 4.0,
        "docs": 1,
        "topSku": "LAM",
        "lastDate": "2026-01-09"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS321",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 162.0,
        "qty": 3.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-01-06"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D315",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 154.5,
        "qty": 4.0,
        "docs": 2,
        "topSku": "SKNW",
        "lastDate": "2026-01-16"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J211",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 74.0,
        "qty": 2.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2026-01-13"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY011",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 72.0,
        "qty": 2.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2026-01-17"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "3EV-R0265",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 40.0,
        "qty": 1.0,
        "docs": 1,
        "topSku": "IFACE R",
        "lastDate": "2026-01-08"
      }
    ]
  },
  "2026-02": {
    "stateStatus": [
      {
        "state": "Pahang",
        "total": 379,
        "active": 375,
        "inactive": 0,
        "missing": 4,
        "activeRate": 98.9,
        "sales": 1098802.09
      },
      {
        "state": "Terengganu",
        "total": 334,
        "active": 331,
        "inactive": 0,
        "missing": 3,
        "activeRate": 99.1,
        "sales": 512394.0
      },
      {
        "state": "Kelantan",
        "total": 340,
        "active": 340,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 377124.33
      }
    ],
    "agentStatus": [
      {
        "state": "Kelantan",
        "agent": "BEN",
        "total": 50,
        "active": 50,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 20463.0
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "total": 87,
        "active": 87,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 209631.23
      },
      {
        "state": "Kelantan",
        "agent": "KI-MI",
        "total": 100,
        "active": 100,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 46130.0
      },
      {
        "state": "Kelantan",
        "agent": "YI",
        "total": 103,
        "active": 103,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 100900.1
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "total": 92,
        "active": 91,
        "inactive": 0,
        "missing": 1,
        "activeRate": 98.9,
        "sales": 314402.2
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "total": 88,
        "active": 88,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 247043.78
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "total": 99,
        "active": 98,
        "inactive": 0,
        "missing": 1,
        "activeRate": 99.0,
        "sales": 329934.53
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "total": 100,
        "active": 98,
        "inactive": 0,
        "missing": 2,
        "activeRate": 98.0,
        "sales": 207421.58
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "total": 130,
        "active": 129,
        "inactive": 0,
        "missing": 1,
        "activeRate": 99.2,
        "sales": 116248.5
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "total": 107,
        "active": 107,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 241472.5
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "total": 97,
        "active": 95,
        "inactive": 0,
        "missing": 2,
        "activeRate": 97.9,
        "sales": 154673.0
      }
    ],
    "watchlist": [
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J211",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 575.0,
        "qty": 15.0,
        "docs": 2,
        "topSku": "90",
        "lastDate": "2026-02-22"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D270",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 532.0,
        "qty": 14.0,
        "docs": 2,
        "topSku": "SKNW",
        "lastDate": "2026-02-09"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "3EV-L0392",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 389.0,
        "qty": 8.0,
        "docs": 1,
        "topSku": "JDB",
        "lastDate": "2026-02-11"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D318",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 376.0,
        "qty": 6.0,
        "docs": 1,
        "topSku": "JDB",
        "lastDate": "2026-02-22"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS321",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 324.0,
        "qty": 6.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-02-21"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "300-C134",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 280.0,
        "qty": 10.0,
        "docs": 1,
        "topSku": "BISON-R",
        "lastDate": "2026-02-27"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "3EV-R0025",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 184.0,
        "qty": 4.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2026-02-04"
      }
    ]
  },
  "2026-03": {
    "stateStatus": [
      {
        "state": "Pahang",
        "total": 391,
        "active": 391,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 1596645.65
      },
      {
        "state": "Terengganu",
        "total": 340,
        "active": 340,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 694145.5
      },
      {
        "state": "Kelantan",
        "total": 353,
        "active": 353,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 563633.93
      }
    ],
    "agentStatus": [
      {
        "state": "Kelantan",
        "agent": "BEN",
        "total": 60,
        "active": 60,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 49659.0
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "total": 90,
        "active": 90,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 272745.63
      },
      {
        "state": "Kelantan",
        "agent": "KI-MI",
        "total": 108,
        "active": 108,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 66390.5
      },
      {
        "state": "Kelantan",
        "agent": "YI",
        "total": 95,
        "active": 95,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 174838.8
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "total": 97,
        "active": 97,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 485378.9
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "total": 90,
        "active": 90,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 347482.68
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "total": 107,
        "active": 107,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 457200.73
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "total": 97,
        "active": 97,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 306583.34
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "total": 126,
        "active": 126,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 179089.0
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "total": 113,
        "active": 113,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 330411.5
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "total": 102,
        "active": 102,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 184645.0
      }
    ],
    "watchlist": []
  },
  "2026-04": {
    "stateStatus": [
      {
        "state": "Pahang",
        "total": 383,
        "active": 383,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 1191494.13
      },
      {
        "state": "Terengganu",
        "total": 366,
        "active": 366,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 567037.5
      },
      {
        "state": "Kelantan",
        "total": 354,
        "active": 354,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 465706.01
      }
    ],
    "agentStatus": [
      {
        "state": "Kelantan",
        "agent": "BEN",
        "total": 61,
        "active": 61,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 48422.4
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "total": 98,
        "active": 98,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 221728.31
      },
      {
        "state": "Kelantan",
        "agent": "KI-MI",
        "total": 107,
        "active": 107,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 61271.0
      },
      {
        "state": "Kelantan",
        "agent": "YI",
        "total": 88,
        "active": 88,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 134284.3
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "total": 94,
        "active": 94,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 314235.25
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "total": 92,
        "active": 92,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 252000.08
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "total": 100,
        "active": 100,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 405144.67
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "total": 97,
        "active": 97,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 220114.13
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "total": 133,
        "active": 133,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 128176.5
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "total": 121,
        "active": 121,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 271552.5
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "total": 112,
        "active": 112,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 167308.5
      }
    ],
    "watchlist": []
  },
  "2026-05": {
    "stateStatus": [
      {
        "state": "Pahang",
        "total": 462,
        "active": 458,
        "inactive": 0,
        "missing": 4,
        "activeRate": 99.1,
        "sales": 1228315.42
      },
      {
        "state": "Terengganu",
        "total": 353,
        "active": 349,
        "inactive": 0,
        "missing": 4,
        "activeRate": 98.9,
        "sales": 516029.0
      },
      {
        "state": "Kelantan",
        "total": 308,
        "active": 307,
        "inactive": 0,
        "missing": 1,
        "activeRate": 99.7,
        "sales": 372454.38
      }
    ],
    "agentStatus": [
      {
        "state": "Kelantan",
        "agent": "BEN",
        "total": 46,
        "active": 46,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 20889.7
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "total": 90,
        "active": 89,
        "inactive": 0,
        "missing": 1,
        "activeRate": 98.9,
        "sales": 188786.5
      },
      {
        "state": "Kelantan",
        "agent": "KI-MI",
        "total": 84,
        "active": 84,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 46443.5
      },
      {
        "state": "Kelantan",
        "agent": "YI",
        "total": 88,
        "active": 88,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 116334.68
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "total": 97,
        "active": 96,
        "inactive": 0,
        "missing": 1,
        "activeRate": 99.0,
        "sales": 278714.2
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "total": 75,
        "active": 74,
        "inactive": 0,
        "missing": 1,
        "activeRate": 98.7,
        "sales": 222142.95
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "total": 99,
        "active": 99,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 353339.1
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "total": 94,
        "active": 93,
        "inactive": 0,
        "missing": 1,
        "activeRate": 98.9,
        "sales": 183757.59
      },
      {
        "state": "Pahang",
        "agent": "XIAN",
        "total": 97,
        "active": 96,
        "inactive": 0,
        "missing": 1,
        "activeRate": 99.0,
        "sales": 190361.58
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "total": 131,
        "active": 130,
        "inactive": 0,
        "missing": 1,
        "activeRate": 99.2,
        "sales": 102945.0
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "total": 127,
        "active": 124,
        "inactive": 0,
        "missing": 3,
        "activeRate": 97.6,
        "sales": 267845.5
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "total": 95,
        "active": 95,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 145238.5
      }
    ],
    "watchlist": [
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J258",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1807.0,
        "qty": 47.0,
        "docs": 1,
        "topSku": "IMP-001",
        "lastDate": "2026-05-21"
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "code": "300-KT211",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1500.0,
        "qty": 25.0,
        "docs": 1,
        "topSku": "JDB",
        "lastDate": "2026-05-20"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY344",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 666.0,
        "qty": 15.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-21"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D330",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 473.5,
        "qty": 11.0,
        "docs": 1,
        "topSku": "TR-002",
        "lastDate": "2026-05-21"
      },
      {
        "state": "Pahang",
        "agent": "XIAN",
        "code": "300-H298",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 309.0,
        "qty": 7.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-20"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "3EV-R0588",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 243.0,
        "qty": 5.0,
        "docs": 1,
        "topSku": "BISON-R",
        "lastDate": "2026-05-21"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS336",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 170.0,
        "qty": 4.0,
        "docs": 1,
        "topSku": "TR-002",
        "lastDate": "2026-05-20"
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "code": "300-WK090",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 158.5,
        "qty": 4.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2026-05-13"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY345",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 148.0,
        "qty": 2.0,
        "docs": 1,
        "topSku": "JDB",
        "lastDate": "2026-05-21"
      }
    ]
  },
  "all": {
    "stateStatus": [
      {
        "state": "Pahang",
        "total": 717,
        "active": 678,
        "inactive": 0,
        "missing": 39,
        "activeRate": 94.6,
        "sales": 9704157.77
      },
      {
        "state": "Terengganu",
        "total": 552,
        "active": 529,
        "inactive": 0,
        "missing": 23,
        "activeRate": 95.8,
        "sales": 4213769.0
      },
      {
        "state": "Kelantan",
        "total": 565,
        "active": 558,
        "inactive": 0,
        "missing": 7,
        "activeRate": 98.8,
        "sales": 3440131.45
      }
    ],
    "agentStatus": [
      {
        "state": "Kelantan",
        "agent": "BEN",
        "total": 108,
        "active": 105,
        "inactive": 0,
        "missing": 3,
        "activeRate": 97.2,
        "sales": 308662.1
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "total": 134,
        "active": 132,
        "inactive": 0,
        "missing": 2,
        "activeRate": 98.5,
        "sales": 1645366.57
      },
      {
        "state": "Kelantan",
        "agent": "KI-MI",
        "total": 177,
        "active": 175,
        "inactive": 0,
        "missing": 2,
        "activeRate": 98.9,
        "sales": 436394.0
      },
      {
        "state": "Kelantan",
        "agent": "YI",
        "total": 156,
        "active": 155,
        "inactive": 0,
        "missing": 1,
        "activeRate": 99.4,
        "sales": 1049708.78
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "total": 132,
        "active": 117,
        "inactive": 0,
        "missing": 15,
        "activeRate": 88.6,
        "sales": 2647101.35
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "total": 173,
        "active": 172,
        "inactive": 0,
        "missing": 1,
        "activeRate": 99.4,
        "sales": 2115272.19
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "total": 146,
        "active": 140,
        "inactive": 0,
        "missing": 6,
        "activeRate": 95.9,
        "sales": 2951080.14
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "total": 174,
        "active": 158,
        "inactive": 0,
        "missing": 16,
        "activeRate": 90.8,
        "sales": 1800342.51
      },
      {
        "state": "Pahang",
        "agent": "XIAN",
        "total": 97,
        "active": 96,
        "inactive": 0,
        "missing": 1,
        "activeRate": 99.0,
        "sales": 190361.58
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "total": 188,
        "active": 182,
        "inactive": 0,
        "missing": 6,
        "activeRate": 96.8,
        "sales": 1070598.0
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "total": 223,
        "active": 209,
        "inactive": 0,
        "missing": 14,
        "activeRate": 93.7,
        "sales": 2119464.5
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "total": 152,
        "active": 149,
        "inactive": 0,
        "missing": 3,
        "activeRate": 98.0,
        "sales": 1023706.5
      }
    ],
    "watchlist": [
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "300-C631",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 6680.0,
        "qty": 180.0,
        "docs": 1,
        "topSku": "90",
        "lastDate": "2025-11-13"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D270",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 5457.2,
        "qty": 146.0,
        "docs": 16,
        "topSku": "SKNW",
        "lastDate": "2026-02-09"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS139",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 4603.0,
        "qty": 120.0,
        "docs": 14,
        "topSku": "EVO",
        "lastDate": "2025-11-21"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J211",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 4544.5,
        "qty": 124.0,
        "docs": 13,
        "topSku": "TR-002",
        "lastDate": "2026-02-22"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "3EV-Q0203",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 3831.0,
        "qty": 105.0,
        "docs": 4,
        "topSku": "EVO",
        "lastDate": "2025-12-11"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D255",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 3676.3,
        "qty": 106.0,
        "docs": 12,
        "topSku": "IFACE B",
        "lastDate": "2026-01-16"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "3EV-L0392",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 3628.0,
        "qty": 88.0,
        "docs": 10,
        "topSku": "SKNR",
        "lastDate": "2026-02-11"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J221",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 3081.75,
        "qty": 90.0,
        "docs": 5,
        "topSku": "SKNR",
        "lastDate": "2026-01-09"
      },
      {
        "state": "Kelantan",
        "agent": "KI-MI",
        "code": "300-KV184",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 2937.0,
        "qty": 71.0,
        "docs": 5,
        "topSku": "EVO",
        "lastDate": "2025-11-17"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J222",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1995.5,
        "qty": 54.0,
        "docs": 5,
        "topSku": "SKNR",
        "lastDate": "2026-01-10"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J258",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1807.0,
        "qty": 47.0,
        "docs": 1,
        "topSku": "IMP-001",
        "lastDate": "2026-05-21"
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "code": "300-KT211",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1500.0,
        "qty": 25.0,
        "docs": 1,
        "topSku": "JDB",
        "lastDate": "2026-05-20"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D315",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1190.5,
        "qty": 32.0,
        "docs": 5,
        "topSku": "CMP",
        "lastDate": "2026-01-16"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D033",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1159.5,
        "qty": 27.0,
        "docs": 4,
        "topSku": "CM-002",
        "lastDate": "2025-11-25"
      },
      {
        "state": "Kelantan",
        "agent": "BEN",
        "code": "300-BR083",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1110.0,
        "qty": 30.0,
        "docs": 2,
        "topSku": "SKNR",
        "lastDate": "2026-01-14"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY299",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1100.0,
        "qty": 25.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2025-10-09"
      },
      {
        "state": "Kelantan",
        "agent": "KI-MI",
        "code": "300-KV215",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1029.0,
        "qty": 21.0,
        "docs": 4,
        "topSku": "CM-002",
        "lastDate": "2025-11-16"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS321",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1014.0,
        "qty": 19.0,
        "docs": 4,
        "topSku": "CM-002",
        "lastDate": "2026-02-21"
      },
      {
        "state": "Kelantan",
        "agent": "BEN",
        "code": "300-KB073",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1010.0,
        "qty": 28.0,
        "docs": 3,
        "topSku": "SKNR",
        "lastDate": "2025-11-05"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D254",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 836.0,
        "qty": 23.0,
        "docs": 4,
        "topSku": "SKNR",
        "lastDate": "2025-12-16"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "300-C253",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 768.5,
        "qty": 21.0,
        "docs": 4,
        "topSku": "TR-002",
        "lastDate": "2025-10-29"
      },
      {
        "state": "Kelantan",
        "agent": "YI",
        "code": "300-KV215",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 686.0,
        "qty": 14.0,
        "docs": 2,
        "topSku": "CM-002",
        "lastDate": "2025-11-27"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY344",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 666.0,
        "qty": 15.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-21"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "3EV-R0025",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 652.0,
        "qty": 14.0,
        "docs": 4,
        "topSku": "EVO",
        "lastDate": "2026-02-04"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J203",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 646.1,
        "qty": 16.0,
        "docs": 2,
        "topSku": "SKNR",
        "lastDate": "2025-11-11"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D299",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 640.0,
        "qty": 16.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2025-12-08"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J234",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 604.0,
        "qty": 15.0,
        "docs": 3,
        "topSku": "SKNR",
        "lastDate": "2025-11-11"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D057",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 585.0,
        "qty": 15.0,
        "docs": 2,
        "topSku": "90",
        "lastDate": "2025-10-15"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "3EV-D0151",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 560.0,
        "qty": 20.0,
        "docs": 2,
        "topSku": "BISON-R",
        "lastDate": "2025-11-13"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D330",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 473.5,
        "qty": 11.0,
        "docs": 1,
        "topSku": "TR-002",
        "lastDate": "2026-05-21"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "3EV-Q0336",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 432.0,
        "qty": 8.0,
        "docs": 3,
        "topSku": "CMP",
        "lastDate": "2025-11-08"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "300-C254",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 382.0,
        "qty": 8.0,
        "docs": 2,
        "topSku": "CM-002",
        "lastDate": "2025-11-12"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D318",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 376.0,
        "qty": 6.0,
        "docs": 1,
        "topSku": "JDB",
        "lastDate": "2026-02-22"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "3EV-L0613",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 360.0,
        "qty": 10.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2025-10-03"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "3EV-Q0141",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 329.0,
        "qty": 7.0,
        "docs": 5,
        "topSku": "LC20",
        "lastDate": "2025-12-11"
      },
      {
        "state": "Pahang",
        "agent": "XIAN",
        "code": "300-H298",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 309.0,
        "qty": 7.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-20"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D214",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 290.5,
        "qty": 7.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2025-10-30"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS243",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 290.0,
        "qty": 8.0,
        "docs": 3,
        "topSku": "EVO",
        "lastDate": "2025-10-31"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "300-C134",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 280.0,
        "qty": 10.0,
        "docs": 1,
        "topSku": "BISON-R",
        "lastDate": "2026-02-27"
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "code": "300-KT185",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 270.0,
        "qty": 5.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2025-10-30"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D290",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 259.0,
        "qty": 7.0,
        "docs": 2,
        "topSku": "EVO",
        "lastDate": "2025-12-11"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY292",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 244.0,
        "qty": 6.0,
        "docs": 2,
        "topSku": "BISON-R",
        "lastDate": "2025-10-16"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "3EV-R0588",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 243.0,
        "qty": 5.0,
        "docs": 1,
        "topSku": "BISON-R",
        "lastDate": "2026-05-21"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-FE249",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 235.0,
        "qty": 5.0,
        "docs": 1,
        "topSku": "SKNW",
        "lastDate": "2025-10-29"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "3EV-Q0215",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 216.0,
        "qty": 4.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2025-10-23"
      },
      {
        "state": "Kelantan",
        "agent": "BEN",
        "code": "3EV-J0110",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 202.0,
        "qty": 4.0,
        "docs": 1,
        "topSku": "TR-002",
        "lastDate": "2025-10-17"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS336",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 170.0,
        "qty": 4.0,
        "docs": 1,
        "topSku": "TR-002",
        "lastDate": "2026-05-20"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "3EV-R0185",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 162.0,
        "qty": 3.0,
        "docs": 1,
        "topSku": "CMX",
        "lastDate": "2025-11-27"
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "code": "300-WK090",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 158.5,
        "qty": 4.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2026-05-13"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J210",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 148.0,
        "qty": 4.0,
        "docs": 2,
        "topSku": "SKNR",
        "lastDate": "2025-12-04"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY345",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 148.0,
        "qty": 2.0,
        "docs": 1,
        "topSku": "JDB",
        "lastDate": "2026-05-21"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D287",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 144.0,
        "qty": 4.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2025-10-02"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY303",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 111.0,
        "qty": 3.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2025-11-27"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY053",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 108.0,
        "qty": 3.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2025-10-17"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "3EV-Q0019",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 94.0,
        "qty": 2.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2025-10-02"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS269",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 90.0,
        "qty": 2.0,
        "docs": 2,
        "topSku": "CMX",
        "lastDate": "2025-10-23"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J186",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 74.5,
        "qty": 2.0,
        "docs": 1,
        "topSku": "DPM EVO",
        "lastDate": "2025-11-07"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY011",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 72.0,
        "qty": 2.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2026-01-17"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY116",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 56.0,
        "qty": 2.0,
        "docs": 1,
        "topSku": "BISON-R",
        "lastDate": "2025-11-28"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY117",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 56.0,
        "qty": 2.0,
        "docs": 1,
        "topSku": "BISON-R",
        "lastDate": "2025-11-28"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J244",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 54.0,
        "qty": 1.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2025-11-25"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J245",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 54.0,
        "qty": 1.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2025-11-25"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D307",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 54.0,
        "qty": 1.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2025-11-24"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS292",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 54.0,
        "qty": 1.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2025-10-24"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "3EV-R0265",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 40.0,
        "qty": 1.0,
        "docs": 1,
        "topSku": "IFACE R",
        "lastDate": "2026-01-08"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "3EV-L0058",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 37.0,
        "qty": 1.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2025-12-04"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY007",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 36.0,
        "qty": 1.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2025-12-27"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY153",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 36.0,
        "qty": 1.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2025-11-27"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY260",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 29.5,
        "qty": 1.0,
        "docs": 1,
        "topSku": "IFACE R",
        "lastDate": "2025-10-31"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "300-C138",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 29.1,
        "qty": 1.0,
        "docs": 1,
        "topSku": "IFACE M",
        "lastDate": "2025-11-18"
      }
    ]
  }
};
