window.debtorStatusData = {
  "may": {
    "stateStatus": [
      {
        "state": "Pahang",
        "total": 434,
        "active": 405,
        "inactive": 2,
        "missing": 27,
        "activeRate": 93.3,
        "sales": 983348.31
      },
      {
        "state": "Terengganu",
        "total": 342,
        "active": 307,
        "inactive": 2,
        "missing": 33,
        "activeRate": 89.8,
        "sales": 439258.5
      },
      {
        "state": "Kelantan",
        "total": 292,
        "active": 278,
        "inactive": 0,
        "missing": 14,
        "activeRate": 95.2,
        "sales": 320247.67
      }
    ],
    "agentStatus": [
      {
        "state": "Kelantan",
        "agent": "BEN",
        "total": 39,
        "active": 37,
        "inactive": 0,
        "missing": 2,
        "activeRate": 94.9,
        "sales": 16491.7
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "total": 87,
        "active": 80,
        "inactive": 0,
        "missing": 7,
        "activeRate": 92.0,
        "sales": 157841.47
      },
      {
        "state": "Kelantan",
        "agent": "KI-MI",
        "total": 84,
        "active": 82,
        "inactive": 0,
        "missing": 2,
        "activeRate": 97.6,
        "sales": 41525.5
      },
      {
        "state": "Kelantan",
        "agent": "YI",
        "total": 82,
        "active": 79,
        "inactive": 0,
        "missing": 3,
        "activeRate": 96.3,
        "sales": 104389.0
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "total": 95,
        "active": 95,
        "inactive": 0,
        "missing": 0,
        "activeRate": 100.0,
        "sales": 245214.95
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "total": 68,
        "active": 62,
        "inactive": 0,
        "missing": 6,
        "activeRate": 91.2,
        "sales": 173413.3
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "total": 93,
        "active": 87,
        "inactive": 0,
        "missing": 6,
        "activeRate": 93.5,
        "sales": 280231.8
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "total": 88,
        "active": 78,
        "inactive": 2,
        "missing": 8,
        "activeRate": 88.6,
        "sales": 143478.94
      },
      {
        "state": "Pahang",
        "agent": "XIAN",
        "total": 90,
        "active": 83,
        "inactive": 0,
        "missing": 7,
        "activeRate": 92.2,
        "sales": 141009.32
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "total": 127,
        "active": 119,
        "inactive": 0,
        "missing": 8,
        "activeRate": 93.7,
        "sales": 85370.0
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "total": 120,
        "active": 101,
        "inactive": 1,
        "missing": 18,
        "activeRate": 84.2,
        "sales": 223347.0
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "total": 95,
        "active": 87,
        "inactive": 1,
        "missing": 7,
        "activeRate": 91.6,
        "sales": 130541.5
      }
    ],
    "watchlist": [
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "3EV-B0223",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 4640.0,
        "qty": 1000.0,
        "docs": 2,
        "topSku": "CM-002",
        "lastDate": "2026-05-18"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "300-C268",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 4500.0,
        "qty": 1100.0,
        "docs": 1,
        "topSku": "TR-002",
        "lastDate": "2026-05-18"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY335",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 4056.5,
        "qty": 936.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-08"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D329",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 3210.0,
        "qty": 800.0,
        "docs": 2,
        "topSku": "EVO",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY297",
        "name": "ABAR JE",
        "maintAgent": "KF",
        "maintType": "ST-Site",
        "status": "Inactive",
        "sales": 3090.0,
        "qty": 700.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-15"
      },
      {
        "state": "Pahang",
        "agent": "XIAN",
        "code": "300-H292",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 2460.0,
        "qty": 470.0,
        "docs": 1,
        "topSku": "GB",
        "lastDate": "2026-05-04"
      },
      {
        "state": "Kelantan",
        "agent": "YI",
        "code": "300-KV249",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 2210.0,
        "qty": 600.0,
        "docs": 2,
        "topSku": "BISON-R",
        "lastDate": "2026-05-15"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D328",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 2056.0,
        "qty": 410.0,
        "docs": 2,
        "topSku": "TR-002",
        "lastDate": "2026-05-13"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY339",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 2050.0,
        "qty": 500.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "300-KH297",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1640.0,
        "qty": 400.0,
        "docs": 2,
        "topSku": "EVO",
        "lastDate": "2026-05-11"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY340",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1545.0,
        "qty": 300.0,
        "docs": 1,
        "topSku": "JDB",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY334",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1210.0,
        "qty": 300.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2026-05-08"
      },
      {
        "state": "Pahang",
        "agent": "XIAN",
        "code": "300-H293",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1052.0,
        "qty": 220.0,
        "docs": 2,
        "topSku": "CM-002",
        "lastDate": "2026-05-16"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D326",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 912.0,
        "qty": 120.0,
        "docs": 1,
        "topSku": "AMR12",
        "lastDate": "2026-05-08"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS332",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 909.0,
        "qty": 220.0,
        "docs": 3,
        "topSku": "SKNR",
        "lastDate": "2026-05-18"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY333",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 837.0,
        "qty": 180.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-08"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "3EV-B0235",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 836.0,
        "qty": 170.0,
        "docs": 2,
        "topSku": "TR-002",
        "lastDate": "2026-05-15"
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "code": "300-WK086",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 810.0,
        "qty": 150.0,
        "docs": 2,
        "topSku": "TR20",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-J135",
        "name": "PAK MISAI (ASLI)",
        "maintAgent": "LEON",
        "maintType": "SH-Shop",
        "status": "Inactive",
        "sales": 750.0,
        "qty": 200.0,
        "docs": 1,
        "topSku": "TR-002",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D324",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 713.0,
        "qty": 160.0,
        "docs": 3,
        "topSku": "TR-002",
        "lastDate": "2026-05-15"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS335",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 709.0,
        "qty": 170.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2026-05-08"
      },
      {
        "state": "Kelantan",
        "agent": "BEN",
        "code": "300-BR087",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 705.0,
        "qty": 150.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-05"
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "code": "300-KT207",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 694.0,
        "qty": 130.0,
        "docs": 2,
        "topSku": "RE16-60",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY337",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 643.5,
        "qty": 90.0,
        "docs": 2,
        "topSku": "AMR12",
        "lastDate": "2026-05-18"
      },
      {
        "state": "Pahang",
        "agent": "XIAN",
        "code": "300-H296",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 570.0,
        "qty": 100.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-09"
      },
      {
        "state": "Pahang",
        "agent": "XIAN",
        "code": "300-H297",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 541.0,
        "qty": 100.0,
        "docs": 1,
        "topSku": "JGI",
        "lastDate": "2026-05-12"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "3EV-Q1049",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 513.0,
        "qty": 90.0,
        "docs": 2,
        "topSku": "CM-002",
        "lastDate": "2026-05-17"
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "code": "300-KT210",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 500.0,
        "qty": 100.0,
        "docs": 1,
        "topSku": "RE16-60",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "300-C267",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 470.0,
        "qty": 100.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-07"
      },
      {
        "state": "Pahang",
        "agent": "XIAN",
        "code": "300-H294",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 460.0,
        "qty": 100.0,
        "docs": 2,
        "topSku": "TR-002",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "code": "300-KT209",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 442.0,
        "qty": 110.0,
        "docs": 1,
        "topSku": "TEX RED",
        "lastDate": "2026-05-13"
      },
      {
        "state": "Kelantan",
        "agent": "YI",
        "code": "3EV-Q1033",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 420.0,
        "qty": 100.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2026-05-05"
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "code": "300-KB101",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 410.0,
        "qty": 100.0,
        "docs": 2,
        "topSku": "EVO",
        "lastDate": "2026-05-13"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY328",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 400.0,
        "qty": 100.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2026-05-07"
      },
      {
        "state": "Kelantan",
        "agent": "KI-MI",
        "code": "300-KM191",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 400.0,
        "qty": 100.0,
        "docs": 1,
        "topSku": "SKNW",
        "lastDate": "2026-05-13"
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "code": "3EV-R0567",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 395.0,
        "qty": 50.0,
        "docs": 1,
        "topSku": "TR20",
        "lastDate": "2026-05-18"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS334",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 360.0,
        "qty": 80.0,
        "docs": 2,
        "topSku": "LAM",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D223",
        "name": "ALVARIZI (工地杂货店）",
        "maintAgent": "LEON",
        "maintType": "ST-Site",
        "status": "Inactive",
        "sales": 356.0,
        "qty": 80.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-02"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY331",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 285.0,
        "qty": 50.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-08"
      },
      {
        "state": "Kelantan",
        "agent": "BEN",
        "code": "3EV-Q1022",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 275.0,
        "qty": 50.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-05"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "3EV-Q0749",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 250.0,
        "qty": 50.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2026-05-12"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "3EV-B0121",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 211.0,
        "qty": 40.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2026-05-15"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY326",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 205.0,
        "qty": 50.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2026-05-13"
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "code": "3EV-B0251",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 171.0,
        "qty": 30.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2026-05-07"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "3EV-B0256",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 171.0,
        "qty": 30.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-11"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY338",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 169.5,
        "qty": 40.0,
        "docs": 2,
        "topSku": "EVO",
        "lastDate": "2026-05-18"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "3EV-Q1008",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 159.0,
        "qty": 28.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2026-05-06"
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "code": "300-WK090",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 158.5,
        "qty": 40.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2026-05-13"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY332",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 152.0,
        "qty": 20.0,
        "docs": 2,
        "topSku": "AMR12",
        "lastDate": "2026-05-15"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY329",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 148.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "JDB",
        "lastDate": "2026-05-07"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "300-JS272",
        "name": "DAMIL (N USER) 没有要order",
        "maintAgent": "JAMES",
        "maintType": "P-Personal",
        "status": "Inactive",
        "sales": 145.0,
        "qty": 28.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2026-05-09"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY327",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 137.5,
        "qty": 30.0,
        "docs": 2,
        "topSku": "CMP",
        "lastDate": "2026-05-15"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "3EV-B0258",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 134.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "TR20",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY330",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 123.0,
        "qty": 30.0,
        "docs": 2,
        "topSku": "EVO",
        "lastDate": "2026-05-13"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "3EV-Q1047",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 114.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2026-05-07"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "3EV-R0526",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 114.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2026-05-08"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "3EV-Q1062",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 114.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "CMX",
        "lastDate": "2026-05-11"
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "code": "3EV-Q1053",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 114.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-11"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "3EV-Q1066",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 114.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "CMX",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "3EV-R0576",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 114.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2026-05-15"
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "code": "3EV-B0202",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 108.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "DPM EVO",
        "lastDate": "2026-05-09"
      },
      {
        "state": "Pahang",
        "agent": "XIAN",
        "code": "3EV-B0250",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 100.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "TR-002",
        "lastDate": "2026-05-07"
      },
      {
        "state": "Kelantan",
        "agent": "YI",
        "code": "3EV-B0217",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 98.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "LWM",
        "lastDate": "2026-05-15"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS333",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 90.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "LAM",
        "lastDate": "2026-05-07"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "3EV-R0558",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 90.0,
        "qty": 16.0,
        "docs": 1,
        "topSku": "IFACE B",
        "lastDate": "2026-05-08"
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "code": "3EV-B0260",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 90.0,
        "qty": 16.0,
        "docs": 1,
        "topSku": "IFACE R",
        "lastDate": "2026-05-15"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "300-KH298",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 74.0,
        "qty": 10.0,
        "docs": 1,
        "topSku": "JDB",
        "lastDate": "2026-05-15"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "300-KH299",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 74.0,
        "qty": 10.0,
        "docs": 1,
        "topSku": "JDB",
        "lastDate": "2026-05-18"
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "code": "3EV-Q1041",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 57.0,
        "qty": 10.0,
        "docs": 1,
        "topSku": "CMX",
        "lastDate": "2026-05-11"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS331",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 57.0,
        "qty": 10.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-15"
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "code": "3EV-R0549",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 55.0,
        "qty": 10.0,
        "docs": 1,
        "topSku": "LAM",
        "lastDate": "2026-05-07"
      },
      {
        "state": "Kelantan",
        "agent": "KI-MI",
        "code": "3EV-R0575",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 55.0,
        "qty": 10.0,
        "docs": 1,
        "topSku": "LWM",
        "lastDate": "2026-05-16"
      },
      {
        "state": "Pahang",
        "agent": "XIAN",
        "code": "3EV-R0532",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 55.0,
        "qty": 10.0,
        "docs": 1,
        "topSku": "LWM",
        "lastDate": "2026-05-16"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "3EV-R0566",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 52.0,
        "qty": 10.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2026-05-11"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY336",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 41.0,
        "qty": 10.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2026-05-11"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY343",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 41.0,
        "qty": 10.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2026-05-18"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY341",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 34.5,
        "qty": 8.0,
        "docs": 1,
        "topSku": "IFACE B",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY342",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 34.5,
        "qty": 8.0,
        "docs": 1,
        "topSku": "IFACE B",
        "lastDate": "2026-05-15"
      }
    ]
  },
  "all": {
    "stateStatus": [
      {
        "state": "Pahang",
        "total": 605,
        "active": 566,
        "inactive": 3,
        "missing": 36,
        "activeRate": 93.6,
        "sales": 4870191.43
      },
      {
        "state": "Terengganu",
        "total": 457,
        "active": 413,
        "inactive": 5,
        "missing": 39,
        "activeRate": 90.4,
        "sales": 2212934.25
      },
      {
        "state": "Kelantan",
        "total": 443,
        "active": 416,
        "inactive": 0,
        "missing": 27,
        "activeRate": 93.9,
        "sales": 1727221.94
      }
    ],
    "agentStatus": [
      {
        "state": "Kelantan",
        "agent": "BEN",
        "total": 77,
        "active": 71,
        "inactive": 0,
        "missing": 6,
        "activeRate": 92.2,
        "sales": 134956.1
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "total": 114,
        "active": 105,
        "inactive": 0,
        "missing": 9,
        "activeRate": 92.1,
        "sales": 862628.64
      },
      {
        "state": "Kelantan",
        "agent": "KI-MI",
        "total": 133,
        "active": 125,
        "inactive": 0,
        "missing": 8,
        "activeRate": 94.0,
        "sales": 215882.0
      },
      {
        "state": "Kelantan",
        "agent": "YI",
        "total": 119,
        "active": 115,
        "inactive": 0,
        "missing": 4,
        "activeRate": 96.6,
        "sales": 513755.2
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "total": 110,
        "active": 109,
        "inactive": 1,
        "missing": 0,
        "activeRate": 99.1,
        "sales": 1359231.3
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "total": 145,
        "active": 134,
        "inactive": 0,
        "missing": 11,
        "activeRate": 92.4,
        "sales": 1019939.84
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "total": 130,
        "active": 124,
        "inactive": 0,
        "missing": 6,
        "activeRate": 95.4,
        "sales": 1472412.98
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "total": 130,
        "active": 116,
        "inactive": 2,
        "missing": 12,
        "activeRate": 89.2,
        "sales": 877597.99
      },
      {
        "state": "Pahang",
        "agent": "XIAN",
        "total": 90,
        "active": 83,
        "inactive": 0,
        "missing": 7,
        "activeRate": 92.2,
        "sales": 141009.32
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "total": 155,
        "active": 146,
        "inactive": 0,
        "missing": 9,
        "activeRate": 94.2,
        "sales": 509596.5
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "total": 165,
        "active": 144,
        "inactive": 2,
        "missing": 19,
        "activeRate": 87.3,
        "sales": 1066877.75
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "total": 137,
        "active": 123,
        "inactive": 3,
        "missing": 11,
        "activeRate": 89.8,
        "sales": 636460.0
      }
    ],
    "watchlist": [
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "code": "300-KT208",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 11410.0,
        "qty": 2500.0,
        "docs": 2,
        "topSku": "SKNW",
        "lastDate": "2026-04-27"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "3EV-B0223",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 6490.0,
        "qty": 1350.0,
        "docs": 3,
        "topSku": "CM-002",
        "lastDate": "2026-05-18"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "300-C268",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 4500.0,
        "qty": 1100.0,
        "docs": 1,
        "topSku": "TR-002",
        "lastDate": "2026-05-18"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY335",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 4056.5,
        "qty": 936.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-08"
      },
      {
        "state": "Kelantan",
        "agent": "YI",
        "code": "300-KV249",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 3794.0,
        "qty": 1080.0,
        "docs": 3,
        "topSku": "BISON-R",
        "lastDate": "2026-05-15"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D329",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 3210.0,
        "qty": 800.0,
        "docs": 2,
        "topSku": "EVO",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY297",
        "name": "ABAR JE",
        "maintAgent": "KF",
        "maintType": "ST-Site",
        "status": "Inactive",
        "sales": 3090.0,
        "qty": 700.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-15"
      },
      {
        "state": "Pahang",
        "agent": "XIAN",
        "code": "300-H292",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 2460.0,
        "qty": 470.0,
        "docs": 1,
        "topSku": "GB",
        "lastDate": "2026-05-04"
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "code": "300-KT207",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 2432.0,
        "qty": 440.0,
        "docs": 5,
        "topSku": "CM-002",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D328",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 2056.0,
        "qty": 410.0,
        "docs": 2,
        "topSku": "TR-002",
        "lastDate": "2026-05-13"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY339",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 2050.0,
        "qty": 500.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "code": "300-WK086",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1978.0,
        "qty": 370.0,
        "docs": 4,
        "topSku": "TR20",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "300-KH297",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1845.0,
        "qty": 450.0,
        "docs": 3,
        "topSku": "EVO",
        "lastDate": "2026-05-11"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D324",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1657.6,
        "qty": 356.0,
        "docs": 7,
        "topSku": "TR-002",
        "lastDate": "2026-05-15"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY340",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1545.0,
        "qty": 300.0,
        "docs": 1,
        "topSku": "JDB",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY334",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1210.0,
        "qty": 300.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2026-05-08"
      },
      {
        "state": "Pahang",
        "agent": "XIAN",
        "code": "300-H293",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 1052.0,
        "qty": 220.0,
        "docs": 2,
        "topSku": "CM-002",
        "lastDate": "2026-05-16"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D326",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 998.0,
        "qty": 140.0,
        "docs": 2,
        "topSku": "AMR12",
        "lastDate": "2026-05-08"
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "code": "300-WK085",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 985.5,
        "qty": 230.0,
        "docs": 1,
        "topSku": "TR-002",
        "lastDate": "2026-04-03"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS332",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 909.0,
        "qty": 220.0,
        "docs": 3,
        "topSku": "SKNR",
        "lastDate": "2026-05-18"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY333",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 837.0,
        "qty": 180.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-08"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "3EV-B0235",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 836.0,
        "qty": 170.0,
        "docs": 2,
        "topSku": "TR-002",
        "lastDate": "2026-05-15"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D325",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 800.0,
        "qty": 200.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2026-04-17"
      },
      {
        "state": "Kelantan",
        "agent": "KI-MI",
        "code": "300-KM191",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 772.0,
        "qty": 200.0,
        "docs": 2,
        "topSku": "SKNW",
        "lastDate": "2026-05-13"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-J135",
        "name": "PAK MISAI (ASLI)",
        "maintAgent": "LEON",
        "maintType": "SH-Shop",
        "status": "Inactive",
        "sales": 750.0,
        "qty": 200.0,
        "docs": 1,
        "topSku": "TR-002",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS335",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 709.0,
        "qty": 170.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2026-05-08"
      },
      {
        "state": "Kelantan",
        "agent": "BEN",
        "code": "300-BR087",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 705.0,
        "qty": 150.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-05"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY326",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 657.0,
        "qty": 120.0,
        "docs": 3,
        "topSku": "JDB",
        "lastDate": "2026-05-13"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY337",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 643.5,
        "qty": 90.0,
        "docs": 2,
        "topSku": "AMR12",
        "lastDate": "2026-05-18"
      },
      {
        "state": "Pahang",
        "agent": "CJ",
        "code": "300-J211",
        "name": "AKAK MALI",
        "maintAgent": "CJ",
        "maintType": "SH-Shop",
        "status": "Inactive",
        "sales": 575.0,
        "qty": 150.0,
        "docs": 2,
        "topSku": "90",
        "lastDate": "2026-02-22"
      },
      {
        "state": "Pahang",
        "agent": "XIAN",
        "code": "300-H296",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 570.0,
        "qty": 100.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-09"
      },
      {
        "state": "Kelantan",
        "agent": "BEN",
        "code": "3EV-Q1022",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 550.0,
        "qty": 100.0,
        "docs": 2,
        "topSku": "CM-002",
        "lastDate": "2026-05-05"
      },
      {
        "state": "Pahang",
        "agent": "XIAN",
        "code": "300-H297",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 541.0,
        "qty": 100.0,
        "docs": 1,
        "topSku": "JGI",
        "lastDate": "2026-05-12"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "3EV-Q1049",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 513.0,
        "qty": 90.0,
        "docs": 2,
        "topSku": "CM-002",
        "lastDate": "2026-05-17"
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "code": "300-KT210",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 500.0,
        "qty": 100.0,
        "docs": 1,
        "topSku": "RE16-60",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "300-C267",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 470.0,
        "qty": 100.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-07"
      },
      {
        "state": "Pahang",
        "agent": "XIAN",
        "code": "300-H294",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 460.0,
        "qty": 100.0,
        "docs": 2,
        "topSku": "TR-002",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "code": "300-KB101",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 451.0,
        "qty": 110.0,
        "docs": 3,
        "topSku": "EVO",
        "lastDate": "2026-05-13"
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "code": "300-WK089",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 445.0,
        "qty": 100.0,
        "docs": 1,
        "topSku": "CMX",
        "lastDate": "2026-04-30"
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "code": "300-KT209",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 442.0,
        "qty": 110.0,
        "docs": 1,
        "topSku": "TEX RED",
        "lastDate": "2026-05-13"
      },
      {
        "state": "Kelantan",
        "agent": "YI",
        "code": "3EV-Q1033",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 420.0,
        "qty": 100.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2026-05-05"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY328",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 400.0,
        "qty": 100.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2026-05-07"
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "code": "3EV-R0567",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 395.0,
        "qty": 50.0,
        "docs": 1,
        "topSku": "TR20",
        "lastDate": "2026-05-18"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "3EV-L0392",
        "name": "AKUWAN",
        "maintAgent": "NMK",
        "maintType": "ST-Site",
        "status": "Inactive",
        "sales": 389.0,
        "qty": 80.0,
        "docs": 1,
        "topSku": "JDB",
        "lastDate": "2026-02-11"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS334",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 360.0,
        "qty": 80.0,
        "docs": 2,
        "topSku": "LAM",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D223",
        "name": "ALVARIZI (工地杂货店）",
        "maintAgent": "LEON",
        "maintType": "ST-Site",
        "status": "Inactive",
        "sales": 356.0,
        "qty": 80.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-02"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY331",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 285.0,
        "qty": 50.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-08"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "3EV-Q1008",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 273.0,
        "qty": 48.0,
        "docs": 2,
        "topSku": "CMX",
        "lastDate": "2026-05-06"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "3EV-Q0749",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 250.0,
        "qty": 50.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2026-05-12"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "3EV-B0213",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 228.0,
        "qty": 40.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-04-18"
      },
      {
        "state": "Kelantan",
        "agent": "BEN",
        "code": "300-KB073",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 222.0,
        "qty": 60.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2026-02-11"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "3EV-B0121",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 211.0,
        "qty": 40.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2026-05-15"
      },
      {
        "state": "Kelantan",
        "agent": "KI-MI",
        "code": "300-KM176",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 209.0,
        "qty": 50.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-02-13"
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "code": "3EV-B0202",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 208.0,
        "qty": 40.0,
        "docs": 2,
        "topSku": "DPM EVO",
        "lastDate": "2026-05-09"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "3EV-R0526",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 204.0,
        "qty": 36.0,
        "docs": 2,
        "topSku": "CMP",
        "lastDate": "2026-05-08"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "300-KH295",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 200.0,
        "qty": 40.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2026-04-22"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "3EV-R0025",
        "name": "M.NAQI ATHALLA",
        "maintAgent": "NMK",
        "maintType": "P-Personal",
        "status": "Inactive",
        "sales": 184.0,
        "qty": 40.0,
        "docs": 1,
        "topSku": "EVO",
        "lastDate": "2026-02-04"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "300-JS331",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 171.0,
        "qty": 30.0,
        "docs": 2,
        "topSku": "CM-002",
        "lastDate": "2026-05-15"
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "code": "3EV-B0251",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 171.0,
        "qty": 30.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2026-05-07"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "3EV-B0256",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 171.0,
        "qty": 30.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-11"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY338",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 169.5,
        "qty": 40.0,
        "docs": 2,
        "topSku": "EVO",
        "lastDate": "2026-05-18"
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "code": "300-WK090",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 158.5,
        "qty": 40.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2026-05-13"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY332",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 152.0,
        "qty": 20.0,
        "docs": 2,
        "topSku": "AMR12",
        "lastDate": "2026-05-15"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY329",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 148.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "JDB",
        "lastDate": "2026-05-07"
      },
      {
        "state": "Terengganu",
        "agent": "NMK",
        "code": "300-JS272",
        "name": "DAMIL (N USER) 没有要order",
        "maintAgent": "JAMES",
        "maintType": "P-Personal",
        "status": "Inactive",
        "sales": 145.0,
        "qty": 28.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2026-05-09"
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "code": "300-WK088",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 141.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "AMR12",
        "lastDate": "2026-04-29"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY327",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 137.5,
        "qty": 30.0,
        "docs": 2,
        "topSku": "CMP",
        "lastDate": "2026-05-15"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "3EV-B0258",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 134.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "TR20",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-BY330",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 123.0,
        "qty": 30.0,
        "docs": 2,
        "topSku": "EVO",
        "lastDate": "2026-05-13"
      },
      {
        "state": "Terengganu",
        "agent": "KF",
        "code": "300-KH275",
        "name": "ABU SAYAP",
        "maintAgent": "NMK",
        "maintType": "P-Personal",
        "status": "Inactive",
        "sales": 114.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-04-16"
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "code": "3EV-Q0999",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 114.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2026-04-23"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "3EV-Q1047",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 114.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2026-05-07"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "3EV-Q1062",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 114.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "CMX",
        "lastDate": "2026-05-11"
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "code": "3EV-Q1053",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 114.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "CM-002",
        "lastDate": "2026-05-11"
      },
      {
        "state": "Pahang",
        "agent": "KW",
        "code": "3EV-Q1066",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 114.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "CMX",
        "lastDate": "2026-05-14"
      },
      {
        "state": "Terengganu",
        "agent": "JAMES",
        "code": "3EV-R0576",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 114.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "CMP",
        "lastDate": "2026-05-15"
      },
      {
        "state": "Pahang",
        "agent": "KEE",
        "code": "3EV-Q1006",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 100.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2026-04-22"
      },
      {
        "state": "Kelantan",
        "agent": "BEN",
        "code": "3EV-B0218",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 100.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "TR-002",
        "lastDate": "2026-04-24"
      },
      {
        "state": "Pahang",
        "agent": "LEON",
        "code": "300-D327",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 100.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "SKNR",
        "lastDate": "2026-04-24"
      },
      {
        "state": "Kelantan",
        "agent": "JACKY",
        "code": "3EV-B0231",
        "name": "",
        "maintAgent": "",
        "maintType": "",
        "status": "Missing",
        "sales": 100.0,
        "qty": 20.0,
        "docs": 1,
        "topSku": "TR-002",
        "lastDate": "2026-04-28"
      }
    ]
  }
};
